### ISSUE TITLE
Any usage of poetry after installation: No module named 'tomli'

### ISSUE THREAD

**Issue by MarcoMeter** [vwxyzjn/cleanrl#455]
## Problem Description
After installing the dependencies via poetry inside a conda environment, any use of poetry results in `ModuleNotFoundError: No module named 'tomli'`.

## Checklist
- [x] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [x] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [x] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Current Behavior

After creating a fresh conda environment, I run `pip install poetry` followed by `poetry install`. So far no errors are logged and it seems that the installation succeeded. But once poetry is used, like `poetry shell` or `poetry install -E docs`, the package tomli cannot be found even though its listed as completed during the first run of `poetry install`.

```
D:\Repositories\cleanrl_ppo_trxl>poetry shell
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\cl\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\cl\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\cl\Scripts\poetry.exe\__main__.py", line 4, in <module>
  File "C:\ProgramData\Anaconda3\envs\cl\lib\site-packages\poetry\console\application.py", line 19, in <module>
    from poetry.__version__ import __version__
  File "C:\ProgramData\Anaconda3\envs\cl\lib\site-packages\poetry\__version__.py", line 5, in <module>
    from poetry.utils._compat import metadata
  File "C:\ProgramData\Anaconda3\envs\cl\lib\site-packages\poetry\utils\_compat.py", line 13, in <module>
    import tomli as tomllib
ModuleNotFoundError: No module named 'tomli
``` 

## Expected Behavior

Open poetry shell or run any documented CleanRL process.

## Possible Solution

1. clone ...
2. `cd cleanrl`
3. `conda create -n cl python=3.10 --yes`
4. `conda activate cl`
5. `pip install poetry`
6. `poetry shell`
7. `poetry install`
8. `poetry run python cleanrl/ppo.py`

## Steps to Reproduce

1. clone ...
2. `cd cleanrl`
3. `conda create -n cl python=3.10 --yes`
4. `conda activate cl`
5. `pip install poetry`
9. `poetry install`
10. `poetry shell` or any other poetry command

## What I tried

- tried Python 3.9 and 3.10
- fresh conda environment
- poetry run pip install tomli
    - Any poetry call causes the ModuleNotFoundError
- pip install tomli
    - Requirement already satisfied

**Comment by JuliusBairaktaris** [comment]
Hey, I am also facing this issue on my institution's cluster. I also tried the Possible Solution by @MarcoMeter which unfortunately also results in the same error.

**Comment by MarcoMeter** [comment]
I believe I had more success with poetry when using the official installer.
https://python-poetry.org/docs/#installing-with-the-official-installer

**Comment by Dikshuy** [comment]
stuck with same issue :/ 
is there any solution to this?
